### ISSUE TITLE
Sort article's tags when creating an article

### ISSUE THREAD

**Issue by pedrommcarrasco** [pedrommcarrasco/CocoaHub.server#3]
We should sort the tags of an article when we create it (`POST` and `PUT`)

**Comment by pedrommcarrasco** [comment]
@VictorBX

**Comment by VictorBX** [comment]
@pedrommcarrasco Two questions
1. Should this also apply to the `Event`, `New`, `NewInput` models?
2. Should the `allowedTags` function also be performed on POST/PUT?

**Comment by pedrommcarrasco** [comment]
Answering your questions @VictorBX:
1. There's no need to update `New`. `NewInput` is the only way you can create or update a `New`
2. That's already being done if I'm not mistaken (in the init)
